
name: Flutter Build

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # Replace with your actual Flutter version

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Ensure Correct Directory
        run: |
          echo "Current directory:"
          pwd
          ls -la

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: flutter pub get
        working-directory: .  # Ensure this points to your project root

      - name: Verify Project Structure
        run: ls -la

      - name: Build APK
        run: flutter build apk
        working-directory: .  # Ensure this points to your project root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
