name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # Replace with your Flutter version

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Debug - Show Directory Structure
        run: |
          echo "Checking current directory:"
          pwd
          ls -la

      - name: Ensure Project Root
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "❌ Error: pubspec.yaml not found in $(pwd)"
            exit 1
          fi

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
